/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as FindBloodRouteImport } from './routes/find-blood'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LipaNaMpesaRouteImport } from './routes/lipa-na-mpesa'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScheduleDonationRouteImport } from './routes/schedule-donation'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsRequestIdRouteImport } from './routes/requests.$requestId'
import { Route as RequestsNewRouteImport } from './routes/requests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const FindBloodRoute = FindBloodRouteImport.update({
  id: '/find-blood',
  path: '/find-blood',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LipaNaMpesaRoute = LipaNaMpesaRouteImport.update({
  id: '/lipa-na-mpesa',
  path: '/lipa-na-mpesa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleDonationRoute = ScheduleDonationRouteImport.update({
  id: '/schedule-donation',
  path: '/schedule-donation',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRoute = RequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/find-blood': typeof FindBloodRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lipa-na-mpesa': typeof LipaNaMpesaRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedule-donation': typeof ScheduleDonationRoute
  '/signin': typeof SigninRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/find-blood': typeof FindBloodRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lipa-na-mpesa': typeof LipaNaMpesaRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedule-donation': typeof ScheduleDonationRoute
  '/signin': typeof SigninRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests': typeof RequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/find-blood': typeof FindBloodRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lipa-na-mpesa': typeof LipaNaMpesaRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedule-donation': typeof ScheduleDonationRoute
  '/signin': typeof SigninRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/donate'
    | '/find-blood'
    | '/forgot-password'
    | '/lipa-na-mpesa'
    | '/profile'
    | '/register'
    | '/schedule-donation'
    | '/signin'
    | '/requests/$requestId'
    | '/requests/new'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/donate'
    | '/find-blood'
    | '/forgot-password'
    | '/lipa-na-mpesa'
    | '/profile'
    | '/register'
    | '/schedule-donation'
    | '/signin'
    | '/requests/$requestId'
    | '/requests/new'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/donate'
    | '/find-blood'
    | '/forgot-password'
    | '/lipa-na-mpesa'
    | '/profile'
    | '/register'
    | '/schedule-donation'
    | '/signin'
    | '/requests/$requestId'
    | '/requests/new'
    | '/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  FindBloodRoute: typeof FindBloodRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LipaNaMpesaRoute: typeof LipaNaMpesaRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ScheduleDonationRoute: typeof ScheduleDonationRoute
  SigninRoute: typeof SigninRoute
  RequestsRequestIdRoute: typeof RequestsRequestIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-blood': {
      id: '/find-blood'
      path: '/find-blood'
      fullPath: '/find-blood'
      preLoaderRoute: typeof FindBloodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lipa-na-mpesa': {
      id: '/lipa-na-mpesa'
      path: '/lipa-na-mpesa'
      fullPath: '/lipa-na-mpesa'
      preLoaderRoute: typeof LipaNaMpesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-donation': {
      id: '/schedule-donation'
      path: '/schedule-donation'
      fullPath: '/schedule-donation'
      preLoaderRoute: typeof ScheduleDonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  FindBloodRoute: FindBloodRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LipaNaMpesaRoute: LipaNaMpesaRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ScheduleDonationRoute: ScheduleDonationRoute,
  SigninRoute: SigninRoute,
  RequestsRequestIdRoute: RequestsRequestIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
